// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvXaRK22TE6URy6IGOO2oMrK3AK3ogAl0',
    appId: '1:811859334874:web:a8ab2da1ddead48cfeb7e3',
    messagingSenderId: '811859334874',
    projectId: 'ninja-brew-cr-be8c9',
    authDomain: 'ninja-brew-cr-be8c9.firebaseapp.com',
    storageBucket: 'ninja-brew-cr-be8c9.appspot.com',
    measurementId: 'G-D3TD2DZK64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlL1b3jw86OyQn2evocymFJ6xrgaf7t9o',
    appId: '1:811859334874:android:44b40b45ad8dbb63feb7e3',
    messagingSenderId: '811859334874',
    projectId: 'ninja-brew-cr-be8c9',
    storageBucket: 'ninja-brew-cr-be8c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIXSp1l1HQZ1oaXpXezK78DdHP5bHY8Lo',
    appId: '1:811859334874:ios:55ac8a7032bad95afeb7e3',
    messagingSenderId: '811859334874',
    projectId: 'ninja-brew-cr-be8c9',
    storageBucket: 'ninja-brew-cr-be8c9.appspot.com',
    iosBundleId: 'com.example.basicsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIXSp1l1HQZ1oaXpXezK78DdHP5bHY8Lo',
    appId: '1:811859334874:ios:1998e40088b27506feb7e3',
    messagingSenderId: '811859334874',
    projectId: 'ninja-brew-cr-be8c9',
    storageBucket: 'ninja-brew-cr-be8c9.appspot.com',
    iosBundleId: 'com.example.basicsFirebase.RunnerTests',
  );
}
